@FinanceTracker.ApiService_HostAddress = https://localhost:6080

GET {{FinanceTracker.ApiService_HostAddress}}/accounts

###

POST {{FinanceTracker.ApiService_HostAddress}}/accounts
Content-Type: application/json
{
  "Name": "Sample Account",
  "OpeningBalance": 1000.00,
  "OpenDate": "2023-10-01",
  "AccountTypeId": 1
}

###

@id=1
GET {{FinanceTracker.ApiService_HostAddress}}/accounts/{{id}}

###

@id=1
GET {{FinanceTracker.ApiService_HostAddress}}/accounts/{{id}}/transactions

###
GET {{FinanceTracker.ApiService_HostAddress}}/accounts/{{id}}/recurringTransactions

###

GET {{FinanceTracker.ApiService_HostAddress}}/accountTypes

###

POST {{FinanceTracker.ApiService_HostAddress}}/accountTypes
Content-Type: application/json
{
  "Type": "TestAccountType"
}

###

GET {{FinanceTracker.ApiService_HostAddress}}/recurringTransactions

###

POST {{FinanceTracker.ApiService_HostAddress}}/recurringTransactions
Content-Type: application/json
{
  "StartDate": "2023-10-01",
  "EndDate": "2030-10-01",
  "Amount": 100.00,
  "AmountVariationPercentage": 5,
  "Description": "Some Sort of Description",
  "RecurrenceCronExpression": "",
  "AccountId": 1,
  "TransactionTypeId": 1,
  "CategoryId": 1
}

###

GET {{FinanceTracker.ApiService_HostAddress}}/transactionCategories

###

POST {{FinanceTracker.ApiService_HostAddress}}/transactionCategories
Content-Type: application/json
{
  "Category": "Groceries",
  "Description": "Groceries, blah, blah"
}
###

GET {{FinanceTracker.ApiService_HostAddress}}/transactionTypes

###

POST {{FinanceTracker.ApiService_HostAddress}}/transactionTypes
Content-Type: application/json
{
  "Type": "TestTransactionType"
}
###

GET {{FinanceTracker.ApiService_HostAddress}}/transactions

###

POST {{FinanceTracker.ApiService_HostAddress}}/transactions
Content-Type: application/json
{
  "TransactionDate": "2023-10-01",
  "Amount": 100.00,
  "Description": "Some Sort of Description",
  "AccountId": 2,
  "TransactionTypeId": 1,
  "CategoryId": 1
}
###

GET {{FinanceTracker.ApiService_HostAddress}}/transactionSplits

###

POST {{FinanceTracker.ApiService_HostAddress}}/transactionSplits
Content-Type: application/json
{
  "TransactionId": 1,
  "Amount": 25.00,
  "Description": "Some Sort of Description",
  "TransactionTypeId": 1,
  "CategoryId": 2
}

###
@id=1
GET {{FinanceTracker.ApiService_HostAddress}}/transactions/{{id}}

###

GET {{FinanceTracker.ApiService_HostAddress}}/transactions/{{id}}/transactionSplits

###
